name: Test React Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Navigate to the correct directory
              run: cd second-action-react
            - name: Install Node.js 18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install the dependencies
              run: npm install
            - name: Run tests
              run: npm test